- name: kerberos user principal created
  command: kadmin.local -q "add_principal -randkey {{ item }}@KAFKA.SECURE"
  register: user_principal
  changed_when: "'already exists' not in user_principal.stderr"
  with_items:
  # User Principals
  - reader
  - writer
  - admin
  # Kafka Service Principals
  - kafka/kafka1
  - kafka/kafka2
  - kafka/kafka3



- name: export user principals to keytab files
  command: 
    cmd: kadmin.local -q "xst -kt /tmp/{{ item }}.user.keytab {{ item }}@KAFKA.SECURE"
    creates: "/tmp/{{ item }}.user.keytab"
  with_items: ['reader', 'writer', 'admin']

- name: export principals to keytab files for kafka service
  command: 
    cmd: kadmin.local -q "xst -kt /tmp/{{ item }}.service.keytab kafka/{{ item }}@KAFKA.SECURE"
    creates: "/tmp/{{ item }}.service.keytab"
  with_items:
    - kafka1
    - kafka2
    - kafka3
    
- name: fetch keytabfiles
  fetch: src="/tmp/{{ item }}.keytab" dest="files/" flat=yes
  with_items:
    - reader.user
    - writer.user
    - admin.user
    - kafka1.service
    - kafka2.service
    - kafka3.service
  
