# file: roles/kafka/tasks/main.yml
- block:
  - setup: gather_subset=network
  - set_fact: ip="{{ ansible_default_ipv4.address }}"
  when: ip is not defined
  tags: ['kafka_setup','zookeeper_setup']
# Disable Swap
# Make host entries
- blockinfile:
    dest: /etc/hosts
    block: |
      # ZooKeeper Servers
      {% for node in groups['zookeeper'] %}
      {{ hostvars[node]['ip'] }} zookeeper{{ hostvars[node]['ZK_ID'] }}
      {% endfor %}
      # Kafka Brokers
      {% for node in groups['kafka'] %}
      {{ hostvars[node]['ip'] }} kafka{{ hostvars[node]['BR_ID'] }}
      {% endfor %}
  tags: ['kafka_setup','zookeeper_setup']
# Install nc
- yum: name=nmap-ncat
- import_tasks: install_kafka.yml
  tags: ['kafka_install']
- import_tasks: setup_zookeeper.yml
  tags: ['zookeeper_setup']
- import_tasks: setup_kafka.yml
  tags: ['kafka_setup']