# file: roles/kafka/tasks/setup_zookeeper.yml
- block:

  - name: zookeeper data dir is present
    file: dest="{{ ZK_DATA_DIR }}" state=directory
  
  - name: set zookeeper node id
    copy: dest="{{ ZK_DATA_DIR }}/myid" content="{{ ZK_ID }}" force=no

  - name: create dir for ssl
    file: dest="{{ KAFKA_HOME }}/config/ssl" state=directory
    when: ZOOKEEPER_SSL is defined and ZOOKEEPER_SSL

  - name: Copy SSL keystore and truststore
    copy: src="{{ item }}" dest="{{ KAFKA_HOME }}/config/ssl/"
    with_items:
      - ssl/kafka.ts.jks
      - "ssl/kafka_zk{{ ZK_ID }}.ks.jks"
    when: ZOOKEEPER_SSL is defined and ZOOKEEPER_SSL


  - name: configure zookeeper
    template: 
      src: zookeeper.properties.jinja 
      dest: "{{ KAFKA_HOME }}/config/zookeeper.properties"
      backup: yes
    notify: restart zookeeper
    
  - name: systemctl for zookeeper
    template: 
      src: zookeeper.service.jinja
      dest: /etc/systemd/system/zookeeper.service
    notify: restart zookeeper
  
  - name: start & enable zookeeper
    systemd: name=zookeeper state=started enabled=yes
  
  when: "'zookeeper' in group_names"  