# file: roles/kafka/tasks/setup_kafka.yml
- block:

  - name: kafka broker log dir is present
    file: dest="{{ BR_LOG_DIR }}" state=directory
  
  - name: Copy SSL keystore and truststore
    copy: src="{{ item }}" dest="{{ KAFKA_HOME }}/config/"
    with_items:
      - "{{ KAFKA_TS_FILE }}"
      - "{{ KAFKA_KS_FILE }}"
    when: ( ZK_SSL is defined and ZK_SSL )  or 
      KAFKA_LISTNERS | selectattr('type','equalto','SSL') | list | count > 0

  - name: configure kafka
    template: 
      src: server.properties.jinja
      dest: "{{ KAFKA_HOME }}/config/server.properties"
      backup: yes
    notify: restart kafka

  - name: copy keytab
    copy: src="kafka{{ BR_ID }}.service.keytab" dest="{{ KAFKA_HOME }}/config/"
    when: KAFKA_SASL is defined and KAFKA_SASL == "GSSAPI"
    
  - name: kafka jaas config
    template:
      src: kafka_jaas.conf.jinja
      dest: "{{ KAFKA_HOME }}/config/kafka_jaas.conf"
    when: KAFKA_SASL is defined and KAFKA_SASL == "GSSAPI"

  - name: systemctl for kafka
    template: 
      src: kafka.service.jinja
      dest: /etc/systemd/system/kafka.service
    notify: restart kafka
      
  - name: start & enable kafka
    systemd: name=kafka state=started enabled=yes
  
  when: "'kafka' in group_names"  